notifications:
  email:
    on_success: change
    on_failure: always

language: python
python:
  # - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - python setup.py develop
  - pip install -r test_requirements.txt

script:
    - py.test
